# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37346d978175f8b4c4ac24b65cc36084bb98d74bf71633fd6791c12fa6ee2877c94434cf0ad6dad1cff1c2551b8c6e287638f5d7e1faf7b99ddc08aa4f07677c

test:
  secret_key_base: 7e6ca456ad774fc21966baff6d2b733fa617e633c99565faa79ff97ba544b4efff580b834121854cc44dbc85f50690c0ac9ce613b202ee3e1dba54a979be00b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
